import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavSidebar from '@/components/NavSidebar';
import TopNavbar from '@/components/TopNavbar';
import DynamicBreadcrumbs from '@/components/DynamicBreadcrumbs';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="fixed top-0 w-full z-50 h-16">
          <TopNavbar />
        </div>
        <div className="flex min-h-screen">
          <NavSidebar />
          <main className="flex-1 p-4 lg:p-8 lg:ml-0 mt-8">
            <DynamicBreadcrumbs /> 
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}